# Generated by Django 4.1 on 2022-08-04 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="appoinment",
        ),
        migrations.AddField(
            model_name="agenda",
            name="customer",
            field=models.ForeignKey(
                default='001',
                on_delete=django.db.models.deletion.CASCADE,
                to="citas.customer",
                to_field="curp",
            ),
            preserve_default=False,
        ),
    ]
