# Generated by Django 4.1 on 2022-08-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0002_remove_customer_appoinment_agenda_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenda",
            name="exid",
        ),
    ]
